// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UploadFileAPI.Entities
{
    public partial class Document
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Imagepath { get; set; }

    }
}